spring:
  application:
    name: ai-code-backend
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code
    username: root
    password: 123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 1
  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jackiy.aicode.controller
# knife
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI 配置
#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: your_api_key
#      model-name: deepseek-chat
#      # 开启日志
#      log-requests: true
#      log-responses: true
#      # 最大输出长度
#      max-tokens: 8192
#      # 设置响应格式：严格按照JSON格式输出
#      strict-json-schema: true
#      response-format: json_object
#    # 流式输出模型配置
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: your_api_key
#      model-name: deepseek-chat
#      # 开启日志
#      log-requests: true
#      log-responses: true
#      # 最大输出长度
#      max-tokens: 8192
#      # 设置响应格式：严格按照JSON格式输出
#      strict-json-schema: true
