spring:
  application:
    name: ai-code-backend
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code
    username: root
    password: 123456

server:
  port: 8888
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jackiy.aicode.controller
# knife
knife4j:
  enable: true
  setting:
    language: zh_cn
